files = [
	'stream/assets/*'
]

[meta]
'stream/vehicles.meta' = 'VEHICLE_METADATA_FILE'
'stream/carvariations.meta' = 'VEHICLE_VARIATION_FILE'
'stream/handling.meta' = 'HANDLING_FILE'
'stream/carcols.meta' = 'CARCOLS_FILE'
'stream/vehiclelayouts.meta' = 'VEHICLE_LAYOUTS_FILE'
'stream/audio/buffalosc_game.dat151' = 'AUDIO_GAMEDATA'
'stream/audio/buffalosc_sounds.dat54' = 'AUDIO_SOUNDDATA'
'stream/audio/saspolicen_game.dat151' = 'AUDIO_GAMEDATA'


