export enum APARTMENT_INTERIORS {
    MODERN_APPARTMENT_1 = 0,
    MODERN_APPARTMENT_2 = 1,
    MODERN_APPARTMENT_3 = 2,
    MOODY_APPARTMENT_1 = 3,
    MOODY_APPARTMENT_2 = 4,
    MOODY_APPARTMENT_3 = 5,
    VIBRANT_APPARTMENT_1 = 6,
    VIBRANT_APPARTMENT_2 = 7,
    VIBRANT_APPARTMENT_3 = 8,
}
